### PR TITLE
feat: send course/block tags with the CourseOverview and XBlock sinks

### PR DESCRIPTION
**Pull request by pomegranited**
Tags are stored on the course_block_json/block_data_json, serialized as a list of "tag name=tag value" strings.

If the course/block has no tags, its json "tags" value in the json will be null.

Closes https://github.com/openedx/openedx-aspects/issues/217

**Testing instructions**

Setup:

1. Install this branch in your tutor dev/local environment, e.g
   ```
   tutor config save -a OPENEDX_EXTRA_PIP_REQUIREMENTS="git+https://github.com/openedx/platform-plugin-aspects.git@jill/sync-tags-on-course-sink#egg=platform_plugin_aspects"
   tutor dev launch -I
   ```
1. Enable tagging and use of the Course Authoring MFE by enabling these waffle flags for "everyone":

   ```
   contentstore.new_studio_mfe.use_tagging_taxonomy_list_page
   contentstore.new_studio_mfe.use_new_home_page
   contentstore.new_studio_mfe.use_new_course_outline_page
   contentstore.new_studio_mfe.use_new_unit_page
   ```
1. Set up some sample taxonomies, orgs, and courses.

   E.g. I have mounted edx-platform, and so can do this:

   ```
   cd edx-platform
   git clone https://github.com/open-craft/taxonomy-sample-data
   cd taxonomy-sample-data
   ```

   Update generate.py to provide a valid USER_EMAIL and TAXONOMY_SAMPLE_PATH, e.g
   ```diff
   --- a/generate.py
   +++ b/generate.py
   @@ -200,12 +200,12 @@ def import_tarfile_in_course(tarfile_path, course_key, user_id):
   
    User = get_user_model()

   -USER_EMAIL = "edx@example.com"
   +USER_EMAIL = "superuser@example.com"

    user = User.objects.get(email=USER_EMAIL)

    # Set to path where repo was cloned, eg: /edx/src/taxonomy-sample-data
   -TAXONOMY_SAMPLE_PATH = "/openedx/taxonomy-sample-data"
   +TAXONOMY_SAMPLE_PATH = "/openedx/edx-platform/taxonomy-sample-data"
   ```

   Run the script in the CMS shell:
   ```
   tutor dev run cms bash
   app@2e5e9f0f4f4e:~/edx-platform$ ./manage.py cms shell < taxonomy-sample-data/generate.py
   ```

Testing:

1. Navigate to the Course Authoring MFE and locate a tagged course, e.g.

   http://apps.local.edly.io:2001/course-authoring/course/course-v1:SampleTaxonomyOrg1+STC1+2023_1
1. Navigate to a unit in this course, and click Manage Tags in the right-hand sidebar to Edit Tags and add tags to one or more units.
1. Publish this course.
1. Visit Superset as a superuser.
1. Check that the course_overviews sink contains tag data in its `course_data_json`, e.g.

   ```
   {
      "advertised_start": null, 
      "announcement": null,
      "lowest_passing_grade": 0.5,
      "invitation_only": false,
      "max_student_enrollments_allowed": null,
      "effort": null,
      "enable_proctored_exams": false,
      "entrance_exam_enabled": false,
      "external_id": null,
      "language": "en",
      "tags": "['HierarchicalTaxonomy=hierarchical taxonomy tag 2.5.14', 'HierarchicalTaxonomy=hierarchical taxonomy tag 3.13.28', 'HierarchicalTaxonomy=hierarchical taxonomy tag 3.6.45', 'ESDC Skills and Competencies=Building and Construction', 'Lightcast Open Skills Taxonomy=Stream Processing', 'FlatTaxonomy=flat taxonomy tag 2440']",
   }
   ```
1. Check that the course_blocks sink contains tag data in its `block_data_json`, e.g.

   ```
   {
      "course": "STC1",
      "run": "2023_1",
      "block_type": "about",
      "detached": 1,
      "graded": 0,
      "completion_mode": "",
      "section": 2,
      "subsection": 1,
      "unit": 5,
      "tags": "['ESDC Skills and Competencies=Endurance', 'ESDC Skills and Competencies=Physical Strength Abilities']",
   }
   ```

**Author Notes & Concerns**

1. <strike>There's a bug in the Course Authoring MFE that prevents the Manage Tags UI from saving tags for units (step 2 under Testing). Branch that fixes this: TBD.</strike> fixed by https://github.com/openedx/edx-platform/pull/34490.
2.  <strike>The Manage Tags UI shows a tag count that includes explicit + implicit tags. When tags from a hierarchical taxonomy are serialized for the course/block, only the explicit "leaf" tags are stored, so the counts will differ.</strike> [6055922](https://github.com/openedx/platform-plugin-aspects/pull/41/commits/6055922e75b5582f83f63adaf8fd244338503b92) ensures both implicit and explicit tags are serialized to ClickHouse.
3. Do we need to update the aspects migrations to add a `tags` field to the materialized views [like we do for other block_data_json fields](https://github.com/openedx/tutor-contrib-aspects/blob/main/tutoraspects/templates/aspects/apps/aspects/migrations/alembic/versions/0035_migrate_dictionaries.py#L178)? 

**Merge checklist:**
Check off if complete *or* not applicable:
- [ ] Version bumped
- [ ] Changelog record added
- [ ] Documentation updated (not only docstrings)
- [x] Fixup commits are squashed away
- [x] Unit tests added/updated
- [x] Manual testing instructions provided
- [ ] Noted any: Concerns, dependencies, migration issues, deadlines, tickets

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @pomegranited! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


This is currently a draft pull request. When it is ready for our review and all tests are green, click "Ready for Review", or remove "WIP" from the title, as appropriate.

**Comment by bmtcril** [comment]
Awesome, I hope to have time to test this tomorrow. From the examples it looks like hierarchical taxonomies don't attach each parent tag in the hierarchy, just the leaf node. Is that correct? I imagine people will want to be able to "drill up" as it were, which we wouldn't be able to do on the reporting side without having all of the taxonomies imported.

**Comment by pomegranited** [comment]
@bmtcril  No worries -- I can ensure that the "implicit" parent tags are also exported here.

I'd also appreciate your feedback on how the tags are being stored in Clickhouse.. is that flat list of "taxonomy name=tag value" OK? It's repetitive, in that the "taxonomy name" is repeated for each tag, but I figured it would be easier to query on than some nested structure.

**Comment by pomegranited** [comment]
@bmtcril CC @Ian2012 This is ready for review now -- I've tested it end to end in my tutor dev stack, and it's working now.

> Do we need to update the aspects migrations to add a tags field to the materialized views [like we do for other block_data_json fields](https://github.com/openedx/tutor-contrib-aspects/blob/main/tutoraspects/templates/aspects/apps/aspects/migrations/alembic/versions/0035_migrate_dictionaries.py#L178)?

Open question :)

**Comment by bmtcril** [comment]
I was able to test this locally, thanks for the excellent directions! I think that having a dictionary for the output makes a little more sense. Aside from the storage I'm already worried that someone will name a tag with an "=" in it or something someday. We're already parsing out the JSON from there, a little more hopefully won't hurt. 

I also wrapped the platform import in a try, since this may be used in earlier versions than Redwood. We haven't tested that in a while, however, and probably should.

**Comment by bmtcril** [comment]
I also agree that we don't need a migration at this point, since we're just capturing the data for v1. We can add dbt models for it when we know more about how we want to query these.

**Comment by bmtcril** [comment]
Screenshots of the test...

Screenshot 2024-05-06 at 10 47 12 AM

And the resulting JSON in ClickHouse:

Screenshot 2024-05-06 at 10 48 32 AM

**Review by bmtcril — APPROVED** [review]
This LGTM in the current state, but some of the changes are mine so I'll wait for a thumb or more feedback from @Ian2012 as I think I addressed his comments with my changes?

**Comment by Ian2012** [comment]
@bmtcril Yes, you addressed my concerns here. Just one more comment (not a blocker), does it makes sense to have the nested structured saved?

Instead of 
```json
{
   "tags": {
      "x": [
        "y", "z"
       ]
   }
}
```
use:
```json
{
   "tags": {
      "x": [
        { "y": {"z": null}}
       ]
   }
}
```

It would be way harder to query this, just wanted to make sure we are not losing any context here.

**Review by Ian2012 — APPROVED** [review]

**Comment by bmtcril** [comment]
@Ian2012 that's a good point, but I think we probably don't need that complexity here. When it comes time to start reporting on these we'll need to make a decision about whether to import the whole set of tags to Aspects as well, and the hierarchy can come with it at that point. Otherwise I think this is sufficient to support the filtering cases we've talked about so far. 🤞

**Pull request merged**
