### PR TITLE
feat: allow to embed superset dashboard in instructor dashboard

### PR DESCRIPTION
**Pull request by Ian2012**
See https://github.com/openedx/openedx-aspects/pull/192 for more information

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @Ian2012! Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Review by bmtcril — APPROVED** [review]
🌞

**Comment by openedx-webhooks** [comment]
@Ian2012 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/platform-plugin-aspects&entry.867055334=https://github.com/openedx/platform-plugin-aspects/pull/2&entry.1484655318=https://github.com/Ian2012&entry.752974735=2024-02-29+21:36&entry.1917517419=2024-03-01+13:57&entry.2133058324=Yes) so we can improve your experience in the future.

**Comment by bmtcril** [comment]
@felipemontoya I know that you approved this code for inclusion in Open edX under the EduNEXT CLA elsewhere, but I forgot to ping you here, where people are more likely to look. Can you confirm that here as well?

**Comment by felipemontoya** [comment]
For sure, I commented that in https://github.com/openedx/openedx-aspects/pull/193

As I said there, as the legal representative of edunext and the signer of the CLA I approve the change of license and the inclusion here.

**Pull request merged**
